# Generated by Django 6.0 on 2025-12-29 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('bio', models.TextField(blank=True, help_text='A short description about yourself.', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Button text (e.g., 'My Portfolio')", max_length=60)),
                ('url', models.URLField(help_text='The destination URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.bioprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
