# Generated by Django 6.0 on 2025-12-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='bioprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
    ]
