# Generated by Django 6.0 on 2025-12-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_bioprofile_avatar_alter_bioprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode (Default)'), ('dark', 'Dark Mode (Night)')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='bioprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description about yourself.', max_length=150),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text="Button text (e.g., 'My Portfolio')", max_length=60),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='The destination URL'),
        ),
    ]
