# Generated by Django 6.0 on 2025-12-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_bioprofile_theme_alter_bioprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
